### ISSUE TITLE
Dropdown doesn't work

### ISSUE THREAD

**Issue by sirajcoder** [hc0503/google-translate-flag-dropdown#2]
This google translate flag dropdown doesn't work with bootstrap 5.

**Comment by devdreamsolution** [comment]
Hi @sirajcoder , thanks for using this plugin.

I think jQuery version issue, can you notice all CDN versions which you used.

**Comment by sirajcoder** [comment]
Can you please let me know how to increase dropdown height ?

**Comment by devdreamsolution** [comment]
```css
.btn.dropdown-toggle.selectpicker.btn-default {
    height: 70px;
}
```
